# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/walter/Documents/code/monkeyString/ScorcsoftUI/page_text_compare.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_text_compare(object):
    def setupUi(self, text_compare):
        text_compare.setObjectName("text_compare")
        text_compare.resize(800, 600)
        self.textEdit_1 = QtWidgets.QTextEdit(text_compare)
        self.textEdit_1.setGeometry(QtCore.QRect(10, 10, 780, 260))
        self.textEdit_1.setStyleSheet("QTextEdit {letter-spacing: 2px;}")
        self.textEdit_1.setObjectName("textEdit_1")
        self.textEdit_2 = QtWidgets.QTextEdit(text_compare)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 280, 780, 260))
        self.textEdit_2.setStyleSheet("QTextEdit {letter-spacing: 2px;}")
        self.textEdit_2.setReadOnly(False)
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(text_compare)
        self.pushButton.setGeometry(QtCore.QRect(350, 550, 100, 40))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(text_compare)
        QtCore.QMetaObject.connectSlotsByName(text_compare)

    def retranslateUi(self, text_compare):
        _translate = QtCore.QCoreApplication.translate
        text_compare.setWindowTitle(_translate("text_compare", "Form"))
        self.textEdit_1.setHtml(_translate("text_compare", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton.setText(_translate("text_compare", "整"))
