# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/walter/Documents/code/monkeyString/ScorcsoftUI/page_text_deduplicate.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_text_deduplicate(object):
    def setupUi(self, page_text_deduplicate):
        page_text_deduplicate.setObjectName("page_text_deduplicate")
        page_text_deduplicate.resize(800, 600)
        page_text_deduplicate.setMinimumSize(QtCore.QSize(800, 600))
        page_text_deduplicate.setMaximumSize(QtCore.QSize(8000, 16777215))
        page_text_deduplicate.setStyleSheet("")
        self.label_from_file_title = QtWidgets.QLabel(page_text_deduplicate)
        self.label_from_file_title.setGeometry(QtCore.QRect(10, 10, 360, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_from_file_title.setFont(font)
        self.label_from_file_title.setObjectName("label_from_file_title")
        self.label_from_string_title = QtWidgets.QLabel(page_text_deduplicate)
        self.label_from_string_title.setGeometry(QtCore.QRect(10, 70, 360, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_from_string_title.setFont(font)
        self.label_from_string_title.setObjectName("label_from_string_title")
        self.lineEdit_source_directory_input = QtWidgets.QLineEdit(page_text_deduplicate)
        self.lineEdit_source_directory_input.setGeometry(QtCore.QRect(10, 30, 310, 30))
        self.lineEdit_source_directory_input.setObjectName("lineEdit_source_directory_input")
        self.pushButton_source_directory_button = QtWidgets.QPushButton(page_text_deduplicate)
        self.pushButton_source_directory_button.setGeometry(QtCore.QRect(310, 27, 50, 37))
        self.pushButton_source_directory_button.setObjectName("pushButton_source_directory_button")
        self.pushButton_start = QtWidgets.QPushButton(page_text_deduplicate)
        self.pushButton_start.setGeometry(QtCore.QRect(480, 525, 120, 40))
        self.pushButton_start.setObjectName("pushButton_start")
        self.plainTextEdit_source_text = QtWidgets.QPlainTextEdit(page_text_deduplicate)
        self.plainTextEdit_source_text.setGeometry(QtCore.QRect(10, 90, 360, 390))
        self.plainTextEdit_source_text.setObjectName("plainTextEdit_source_text")
        self.plainTextEdit_result_text = QtWidgets.QPlainTextEdit(page_text_deduplicate)
        self.plainTextEdit_result_text.setGeometry(QtCore.QRect(420, 30, 360, 450))
        self.plainTextEdit_result_text.setObjectName("plainTextEdit_result_text")
        self.label_result_title = QtWidgets.QLabel(page_text_deduplicate)
        self.label_result_title.setGeometry(QtCore.QRect(420, 10, 360, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_result_title.setFont(font)
        self.label_result_title.setObjectName("label_result_title")
        self.label_type_title = QtWidgets.QLabel(page_text_deduplicate)
        self.label_type_title.setGeometry(QtCore.QRect(10, 500, 360, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_type_title.setFont(font)
        self.label_type_title.setObjectName("label_type_title")
        self.checkBox_line = QtWidgets.QCheckBox(page_text_deduplicate)
        self.checkBox_line.setGeometry(QtCore.QRect(10, 530, 360, 20))
        self.checkBox_line.setObjectName("checkBox_line")
        self.checkBox_char = QtWidgets.QCheckBox(page_text_deduplicate)
        self.checkBox_char.setGeometry(QtCore.QRect(10, 560, 360, 20))
        self.checkBox_char.setObjectName("checkBox_char")
        self.pushButton_save_to_file = QtWidgets.QPushButton(page_text_deduplicate)
        self.pushButton_save_to_file.setGeometry(QtCore.QRect(600, 525, 120, 40))
        self.pushButton_save_to_file.setObjectName("pushButton_save_to_file")

        self.retranslateUi(page_text_deduplicate)
        QtCore.QMetaObject.connectSlotsByName(page_text_deduplicate)

    def retranslateUi(self, page_text_deduplicate):
        _translate = QtCore.QCoreApplication.translate
        page_text_deduplicate.setWindowTitle(_translate("page_text_deduplicate", "Form"))
        self.label_from_file_title.setText(_translate("page_text_deduplicate", "对文件内容去重"))
        self.label_from_string_title.setText(_translate("page_text_deduplicate", "对字符串去重"))
        self.pushButton_source_directory_button.setText(_translate("page_text_deduplicate", "..."))
        self.pushButton_start.setText(_translate("page_text_deduplicate", "整"))
        self.label_result_title.setText(_translate("page_text_deduplicate", "去重结果"))
        self.label_type_title.setText(_translate("page_text_deduplicate", "去重方式"))
        self.checkBox_line.setText(_translate("page_text_deduplicate", "删除重复行"))
        self.checkBox_char.setText(_translate("page_text_deduplicate", "删除重复字，\"abbc\"去重为\"abc\""))
        self.pushButton_save_to_file.setText(_translate("page_text_deduplicate", "保存到文件"))
